id: I2348FAFC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T19:46:09+00:00'
last_modified: '2022-06-08T06:47:14.209915+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4307
  title: མངོན་རྟོགས་རྒྱན་གྱི་རྒྱས་བཤད་སྦས་དོན་རབ་གསལ་དང་ཞུགས་གནས་ཀྱི་རྣམ་གཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E3A6:
      image_group_id: I3CN4322
      title: ''
      total_pages: 234
      order: 1
      base_file: E3A6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
