id: P006777
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4307
  title: མངོན་རྟོགས་རྒྱན་གྱི་རྒྱས་བཤད་སྦས་དོན་རབ་གསལ་དང་ཞུགས་གནས་ཀྱི་རྣམ་གཞག
  author: ''
  volumes:
    fc2c6d6e9e7643b1a6cce1d6de68d9a0:
      image_group_id: I3CN4322
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
